on:
  push:
    branches:
      - main



jobs:
  build:
    runs-on: ubuntu-latest


    steps:
      - name: 'Test'
        run: pwd 
      
      - name: 'Say Hi'
        run: echo Hi

      - name: 'Checkout repository'
        uses: actions/checkout@v3
      
      - name: 'Log in to DockerHub'
        run: docker login --username ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_TOKEN }}

      - name: 'Build the image'
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/yaramatter_2023040405 .

      - name: 'Push the image'
        run: docker push ${{ secrets.DOCKER_USERNAME }}/yaramatter_2023040405
      


